name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: switch Node.js to 4.9.1
        uses: actions/setup-node@v1
        with:
          node-version: '4.9.1'
      - name: install node modules for express
          run: npm install
      - name: switch Node.js to 12.16.1
          uses: actions/setup-node@v1
          with:
          node-version: '12.16.1'
      - name: install node modules for angular
        run: cd client && npm install
      - name: build angular app
        run: npm run build
      - name: Deploy to DEV server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/bin"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: Run forever
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.REMOTE_TARGET }}
            forever stopall
            forever start bin/www
            forever list
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
